import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,ChevronDown,ChevronLeft,ChevronRight,Handshake,Home,MoreHorizontal,Phone,Search,UserRound,Users,WalletCards}from'lucide-react';import'./styles.css';
type Kpi={title:string;value:string;delta:string;positive:boolean;icon:React.ReactNode};
const nav=['Home','Developments','Buildings','Units','Leads','Companies','Contacts','Deals','Activities','Attorney Firms','Reports'];
const kpis:Kpi[]=[{title:'Active Listing',value:'23',delta:'-12% ↘',positive:false,icon:<Home/>},{title:'Active Leads',value:'120',delta:'+12% ↗',positive:true,icon:<UserRound/>},{title:'Total Closed',value:'42',delta:'+12% ↗',positive:true,icon:<Handshake/>},{title:'Total Revenue',value:'Rs.22Cr.',delta:'+12% ↗',positive:true,icon:<WalletCards/>}];
const listings=[['Maplewood House','House','12','Rs.85L','125','8/12 Occupied','🏡'],['Serenity Villa','Villa','9300','Rs.2.8Cr','930','Available','🏘️'],['Rosehill Cottage','House','25','Rs.1.1Cr','355','Available','🏠'],['Skyline Edge','Apartment','17','Rs.75L','425','Sold Out','🏙️']];
const contacts=[['John Doe','New York','👨🏻'],['Jessica Chen','California, LA','👩🏻'],['Evan Chris','New York','👨🏼'],['Jack B.','Ohio, Columbus','👨🏻'],['Emily Paris','California, LA','👩🏼']];
const reminders=[['Submit Final Offer- Villa Deal','Finalize and send offer documents.'],['Review Contract with Legal','Ensure attorney reviews apartment deal contract today.'],['Call Jessica Chen – Follow-up','Discuss her feedback after site visit to Angel Plaza.']];
function App(){const[active,setActive]=useState('Home');const[search,setSearch]=useState('');const[offset,setOffset]=useState(0);const month=useMemo(()=>new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(2025,6+offset,1)),[offset]);return <div className="app"><header className="topbar"><div className="brand"><div className="logo"><i/><i/><i/></div><b>REALTOR360</b></div><nav>{nav.map(n=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}>{n}</button>)}<button><MoreHorizontal/></button></nav><div className="actions"><label><input placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/><Search/></label><div className="profile">👨🏽<ChevronDown size={15}/></div></div></header><main className="dashboard"><div className="content"><div className="kpis">{kpis.map(k=><KpiCard key={k.title}{...k}/>)}</div><div className="grid2"><Panel title="Deals by Lead Source"><Donut/></Panel><Panel title="Deals by Stages by Development"><Stages/></Panel></div><div className="grid2"><Panel title="Deals by Sales People by Development"><Sales/></Panel><Panel title="Deals in Pipeline by Development"><Pipeline/></Panel></div><Panel title="Total Deals Closed"><Progress/></Panel><div className="bottom"><Panel title="Active Listing"><Listings/></Panel><Panel title="Leads Contacts"><Contacts/></Panel></div></div><aside><Panel title="Reminder"><div className="follow"><b>Follow-Ups</b><small>15 leads need to be followed up.</small><div>👨🏻👩🏻👨🏼👩🏼 <em>+11</em></div></div><div className="reminders">{reminders.map(r=><div key={r[0]}><b>{r[0]}</b><small>{r[1]}</small></div>)}</div></Panel><Panel><div className="calendarHead"><strong>{month}</strong><div><button onClick={()=>setOffset(v=>v-1)}><ChevronLeft/></button><button onClick={()=>setOffset(v=>v+1)}><ChevronRight/></button></div></div><Calendar offset={offset}/></Panel><Panel title="My Schedule"><div className="schedule">{[['Visit Client- Angel Plaza','Sector 45, Gurugram, Haryana','mint'],['Visit Client – Site Walkthrough','Whitefield Road, Bengaluru, Karnataka','mint'],['Follow Up – Jessica Chen','jessica.chen@email.com','pink'],['Follow Up – Roger Bouchard','roger.bouchard@clientmail.com','pink'],['Submit Final Offer – Villa Deal','Finalize and send offer documents.','yellow'],['Submit Internal Review – Apartment PricingFinal Offer – Villa Deal','Update CRM with latest market rates.','yellow']].map(x=><div className={x[2]} key={x[0]}><b>{x[0]}</b><small>{x[1]}</small></div>)}</div></Panel></aside></main></div>}
function KpiCard(p:Kpi){return <div className="panel kpi"><div className="ico">{p.icon}</div><span>{p.title}</span><div><b>{p.value}</b><em className={p.positive?'pos':'neg'}>{p.delta}</em></div></div>}
function Panel({title,children}:{title?:string;children:React.ReactNode}){return <section className="panel"><div className="inner">{title&&<h2>{title}</h2>}{children}</div></section>}
function Donut(){return <div className="donutArea"><div className="donut"></div><div className="hole"></div><span className="lab a">Website<br/><small>10 (24.83%)</small></span><span className="lab b">Inbound Call<br/><small>9 (37.87%)</small></span><span className="lab c">Reference<br/><small>1 (30.6%)</small></span><span className="lab d">Facebook<br/><small>1 (6.78%)</small></span></div>}
function Stages(){let a=['Interested','Site Visit Done','Unit Shortlisted','Contract Signed','Offer Initiated','Offer Accepted'];return <div className="stage"><div className="bars">{a.map((x,i)=><div key={x}><i style={{height:90+i%2*6}}/><i style={{height:65+i%3*4}}/><i style={{height:32+i%2*5}}/><small>{x}</small></div>)}</div><div className="legend"><span>● Angel Plaza</span><span>● Angel Garden</span><span>● None</span></div></div>}
function Sales(){return <div className="sales"><div className="sale"><i/><i/><i/></div><div className="sale short"><i/><i/><i/></div><div className="ticks">0　 2.5　 5　 7.5　 10　 12.5　 15　 17.5　 20</div><div className="legend"><span>● Angel Plaza</span><span>● Angel Garden</span><span>● None</span></div></div>}
function Pipeline(){return <div className="pipeline"><div><b>Development Name</b><b>Record Count</b></div>{[['None',14],['Angel Plaza',3],['Angel Garden',1]].map(r=><div key={String(r[0])}><span>{r[0]}</span><span>{r[1]}</span></div>)}</div>}
function Progress(){return <div className="progress"><div><i/></div><div className="metrics"><span><b>42</b> Closed Deals</span><span><b>132</b> On Progress</span></div></div>}
function Listings(){return <div className="table"><div className="thead"><span>Property</span><span>Type</span><span>Units</span><span>Price</span><span>Active Leads</span><span>Views</span><span>Status</span></div>{listings.map(l=><div className="tr" key={l[0]}><span className="prop"><i>{l[6]}</i>{l[0]}</span><span>{l[1]}</span><span>{l[2]}</span><span>{l[3]}</span><span>👨🏻 👩🏻 <small>+{l[4].length%4+10}</small></span><span>{l[4]}</span><span className={l[5]==='Sold Out'?'sold':'status'}>{l[5]}</span></div>)}</div>}
function Contacts(){return <div>{contacts.map(c=><div className="contact" key={c[0]}><i>{c[2]}</i><div><b>{c[0]}</b><small>{c[1]}</small></div><button><Phone size={15}/></button></div>)}</div>}
function Calendar({offset}:{offset:number}){const d=new Date(2025,6+offset,1),first=d.getDay(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return <div className="cal"><div className="week">{['S','M','T','W','T','F','S'].map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:42},(_,i)=>{let n=i-first+1;if(n<1)return <span className="muted" key={i}>{new Date(d.getFullYear(),d.getMonth(),0).getDate()+n}</span>;if(n>days)return <span className="muted" key={i}>{n-days}</span>;return <span className={n===8?'today':''} key={i}>{n}</span>})}</div></div>}
createRoot(document.getElementById('root')!).render(<App/>);